### PR TITLE
Add folder

### PR DESCRIPTION
**Pull request by jm189042**
Folder easy with 4 easy level activities

### CODE REVIEW

**Review by ABISHEK-R123 — APPROVED** [review]

**Review by ABISHEK-R123 — COMMENTED** [review]
ABISHEK R

**Comment by ABISHEK-R123** [comment]
During the Java Development internship with CodSoft,I had learned new skills and managed to grow in just a short amount of time Collaborating with them heled me in so many ways Thankyou for he opportunity to be able to upskill and grow with codsoft

**Review by ABISHEK-R123 — APPROVED** [review]
ABISHEK R-Easy Level

**Comment by Durgesh-Vaigandla** [comment]
Guys your doing wrong PR's This is CSEdge not Code soft

**Pull request closed without merging**
